###
POST http://localhost:8080/clients
Content-Type: application/json

{
  "id": null,
  "name": "client 14",
  "phone": "89816106599"
}


###
GET http://localhost:8080/clients

###
GET http://localhost:8080/clients/phone/+79082950000