### todo переделать в маппере, чтобы name и phone были не null у dto
GET http://localhost:8080/reservations?reservationTime=2022-02-02&specialistId=2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
