## 1. Запрос для метода createSpecialist():
POST http://localhost:8080/specialists
Content-Type: application/json

{
  "id": null,
  "name": "specialist 4",
  "phone": "89316108113",
  "procedureIds": [
    2,
    3
  ]
}

###

## 2. Запрос для метода getAllSpecialists():
GET http://localhost:8080/specialists

###

## 3. Запрос для метода getSpecialist():
GET http://localhost:8080/specialists/4

###

## 4. Запрос для метода getAllSpecialistsByProcedure():
GET http://localhost:8080/specialists/by-procedure/2

###

## 5. Запрос для метода updateSpecialist():
PUT http://localhost:8080/specialists/4
Content-Type: application/json

{
  "id": null,
  "name": "specialist 5",
  "phone": "89316100011",
  "procedureIds": [
    1
  ]
}

###

## 6. Запрос для метода addProcedure():
POST http://localhost:8080/specialists/4/procedures/2
###

## 7. Запрос для метода removeProcedure():
DELETE http://localhost:8080/specialists/11/procedures/2

###

## 8. Запрос для метода deleteSpecialist():
DELETE http://localhost:8080/specialists/4

